### ISSUE TITLE
Recognize Existing .eslintrc.* file

### ISSUE THREAD

**Issue by JamesSingleton** [airbnb/ts-migrate#19]
It would be nice to be able to recognize if the folder already has a `.eslintrc.*` file. When I ran this in a folder that had a `.eslintrc.json` file, it created an empty `.eslintrc` file instead of adding to the `.eslintrc.json`.

**Comment by Rudeg** [comment]
In our use-case we had only `.eslintrc` files, that's why the check for existing config is [pretty simple](https://github.com/airbnb/ts-migrate/blob/a4d609a0420ab028f2bf42d6d0df703dc8d7fc76/packages/ts-migrate/bin/ts-migrate-full.sh#L69). It could be definitely improved, would be happy to review a PR!

**Comment by JamesSingleton** [comment]
@Rudeg what is supposed to be placed into the `.eslintrc` file? As when I ran it, it was just empty, is that the desired effect?

**Comment by Rudeg** [comment]
@JamesSingleton It's supposed to be placed only in the case if the project doesn't have it at all. It's used by the [eslint plugin](https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/eslint-fix.ts#L6), to run formatting after the transformations. In our use case, we had it all the time, so there wasn't a problem. But in case of other projects, it's just prevention of the error in the plugin itself. 

Thanks for the fix!
