### ISSUE TITLE
Repeated Migrations result in duplicate `@ts-expect-error ts-migrate(2578)` errors

### ISSUE THREAD

**Issue by pdfowler** [airbnb/ts-migrate#27]
While tracking down issues I was having with the `eslint-plugin` (#21), I ended up running the `ts-migrate-full` script several times. This resulted in a handful of repetitive `@ts-expect-error` directives:

```
147    const newProps = _(assignments)
148    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
149    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
150    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
151    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
152-207     ...
208    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
209    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
210    // @ts-expect-error ts-migrate(2578) FIXME: Unused '@ts-expect-error' directive.
211    // @ts-expect-error ts-migrate(2339) FIXME: Property 'user' does not exist on type 'unknown'.
212    .map(a => ({ user: a.user, dataType: a.dataType, ref: a.ref }))
```

**Comment by zpnk** [comment]
Seeing the same behavior with the `reignore` command. 

In my scenario, running the initial `ts-migrate-full` returned a large number of `@ts-expect-errors` on missing library definitions. After installing the `@types/*`, I ran `reignore` to remove the initial FIXMEs and ended up with twice as many due to the new `unused directive` warnings.

Ideally `ts-migrate-full` / `reignore` would remove any `@ts-expect-errors` that no longer apply.

**Comment by lencioni** [comment]
Thanks for the report! This definitely looks like a bug. Would you be interested in putting up a PR to fix it?

**Comment by Rudeg** [comment]
Thanks for the report! Fixed https://github.com/airbnb/ts-migrate/commit/4b8da40a6cc327e4ba5a6172053098edc5c99fe8.
