### ISSUE TITLE
inline function implicit any support

### ISSUE THREAD

**Issue by ron23** [airbnb/ts-migrate#75]
I think it makes sense to not add `any` to inline functions and it's better to leave them for TS to manually infer. It makes migration a bit easier and safer. Example:

```
// utils.ts  =< TS file
function addOne(input: number): number {
  return input + 1;
}

// foo.js
function f(input) {
  input.map(x => addOne(x))
}

### after ts-migrate runs (foo.ts)

function f(input: any) {
  input.map((x: any) => addOne(x));   // <= I want to keep x implicit
}

// when I type `input` I don't get error on the inline
function g(input: string[]) {
  input.map((x: any) => addOne(x)); // no error
}

// What I want: adding types to f will infer correctly and detect an error
function f(input: string[]) {
  input.map(x => addOne(x)); // Argument of type 'string' is not assignable to parameter of type 'number'.(2345)
}
```

**Comment by edsrzf** [comment]
The reason that ts-migrate adds the `any` is because TypeScript is still flagging an error with the `noImplicitAny: true` option. This link might make it clearer: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwCaoPJgKYAoZgAOIUAXImCALYBG2ATgJTmW0OIDeAUIovdlBD0kBYlEQBqRAEYA3FwC+XLqEiwEiYPiIlyyMAE9GnHolEkAdFWSFcAD0QBeAHwp0WPHcaN5CoA

You're correct that this is a little annoying when you do decide to add the `: string[]` annotation and the annotation for the `map` callback becomes unnecessary.

I'm not sure of the best way to solve this, though. It would be nice if the TypeScript compiler could report unnecessary annotations, maybe.

**Comment by ron23** [comment]
I see, yea that makes sense. Thanks. I'll close.
