### ISSUE TITLE
[explicit-any]:  missing case for error 7008

### ISSUE THREAD

**Issue by ron23** [airbnb/ts-migrate#88]
Looks like `// TS7008: "Member '{0}' implicitly has an 'any' type"` is not covered in explicit-any plugin.
From my experiments looks like the code for 7006 handles the interface case correctly

Example:

```
interface State {
  id;
  name;
}
```

However it doesn't handle this case:
```
export const foo = ({ id}: {
  id?; // this is converted to id: $TSFixMe?;
})
```

_Side note:_
I tried to make a PR but for some reason I'm getting a ton of TS error like (`Binding element 'getLanguageService' implicitly has an 'any' type.ts(7031)` in explicit-any.ts or even `Cannot find module 'ts-migrate-server' or its corresponding type declarations.ts(2307)`.
I ran yarn and yarn build.

**Comment by edsrzf** [comment]
I've created a PR that fixes this.

I'm interested to hear more about the issues you had making a PR. Did you follow the [contributing](https://github.com/airbnb/ts-migrate/blob/master/CONTRIBUTING.md) doc? It sounds like the errors could be due to uninstalled dependencies, and/or having not run `yarn build` at the top level to build all packages?
